# Generated by Django 2.2.1 on 2019-05-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='content',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
