# Generated by Django 2.2.1 on 2019-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_schedule_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='url',
            field=models.TextField(default='haha'),
            preserve_default=False,
        ),
    ]
